### ISSUE TITLE
Platformio can't find simpleDSTadjust.h, no matter what I do...

### ISSUE THREAD

**Issue by PuceBaboon** [neptune2/simpleDSTadjust#1]
This one took me quite some time to pin down.

There's a missing comma after the closing brace of "repository" in the library.json file.

 "repository":
 {
    "type": "git",
    "url": "https://github.com/neptune2/simpleDSPadjust"
 }                                                     <<<<<<<<<<< HERE <<<<<<<<<<<<<<<<<<
 "version": "1.1.0"

This causes platformio to quietly ignore the library, so even it's installed and the "platformio lib list" command confirms that it's there, you still get "simpleDSTadjust.h not found" errors during the compile.

Adding simpleDSTadjust to the local lib directory is the same ("simpleDSTadjust.h not found").

Eventually tracked down by removing files one by one from the library directory until platformio could "see" it again.  Phew!

Note that the "url" line has a typo ("DSP" instead of "DST"), but that's not the cause of the issue.

**Comment by PuceBaboon** [comment]
Oh, and the URL line has a typo, too (but it's not the cause of the problem).

**Comment by neptune2** [comment]
Thanks John, for pointing out these problems.
I have fixed library.json and released a new version.
